### PR TITLE
Update to work with pytorch 0.4

### PR DESCRIPTION
**Pull request by ktarplee**
I am new to pytorch but wanted to get these examples working in the latest pytorch and torchvision.  I thought I would contribute this back to you for review and incorporation into your codebase to keep it up to date.

### CODE REVIEW

**Comment by adambielski** [comment]
Hi @ktarplee ! I'm sorry it's so late, I just noticed your PR. Thanks for your work! I'll try to look through it soon and merge it there are no bugs

**Comment by adambielski** [comment]
@ktarplee it looks good, but needs merging with some of my recent changes (notebooks and readme), plus the notebooks need to be fully executed. I can add necessary commits and merge it if you give me the permissions (https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)

**Comment by ktarplee** [comment]
It looks like you already have permissions.  The "allow edits from maintainers" checkbox is checked.  Go ahead and make the necessary changes.  Thanks.

**Comment by ktarplee** [comment]
If you want me to do anything let me know.  I am using your code in some other work and will likely have some other improvements to send your way once I am at a stopping point.

**Comment by adambielski** [comment]
merged!

**Pull request merged**
